// ==========================================================================
// Agent Control Center — Mock Data
// ==========================================================================

export const agents = [
  {
    id: "daily-morning",
    name: "Daily Driver (Morning)",
    schedule: "Daily 6:00 AM",
    status: "completed",
    lastRun: "Today, 6:02 AM",
    cost: 0.12,
    turns: 8,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["research-assistant", "email-drafting", "calendar-sync"],
    cron: "0 6 * * *",
    permissionMode: "acceptEdits",
    note: null,
    error: null,
  },
  {
    id: "daily-evening",
    name: "Daily Driver (Evening)",
    schedule: "Daily 5:00 PM",
    status: "running",
    lastRun: "In progress",
    cost: 0.00,
    turns: 3,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["research-assistant", "email-drafting", "slack-digest"],
    cron: "0 17 * * *",
    permissionMode: "acceptEdits",
    note: null,
    error: null,
  },
  {
    id: "daily-weekly",
    name: "Daily Driver (Weekly)",
    schedule: "Fridays 4:00 PM",
    status: "completed",
    lastRun: "Feb 28",
    cost: 0.31,
    turns: 18,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["research-assistant", "weekly-report", "notion-sync"],
    cron: "0 16 * * 5",
    permissionMode: "acceptEdits",
    note: null,
    error: null,
  },
  {
    id: "spending",
    name: "Spending Analysis",
    schedule: "Sundays 9:00 AM",
    status: "attention",
    lastRun: "Mar 1",
    cost: 0.48,
    turns: 27,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["finance-analysis", "csv-parser", "budget-alerts"],
    cron: "0 9 * * 0",
    permissionMode: "confirmAll",
    note: "approached budget limit",
    error: null,
  },
  {
    id: "inbox",
    name: "Process Inbox",
    schedule: "Daily 8:00 AM",
    status: "disabled",
    lastRun: "Never",
    cost: 0.00,
    turns: 0,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["email-triage", "label-manager"],
    cron: "0 8 * * *",
    permissionMode: "acceptEdits",
    note: null,
    error: null,
  },
  {
    id: "health",
    name: "Health Audit",
    schedule: "Daily 7:00 PM",
    status: "failed",
    lastRun: "Mar 1",
    cost: 0.05,
    turns: 2,
    maxTurns: 30,
    maxBudget: 0.50,
    skills: ["vault-reader", "health-metrics"],
    cron: "0 19 * * *",
    permissionMode: "acceptEdits",
    note: null,
    error: "vault path not found",
  },
];

// --------------------------------------------------------------------------
// Run History — 25 rows
// --------------------------------------------------------------------------
export const runHistory = [
  { id: 1, date: "2026-03-03", time: "06:02", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.12, durationMs: 42300, turns: 8, notes: "All tasks completed" },
  { id: 2, date: "2026-03-03", time: "17:00", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.08, durationMs: 31200, turns: 5, notes: "Slack digest sent" },
  { id: 3, date: "2026-03-02", time: "06:01", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.14, durationMs: 48700, turns: 10, notes: "Calendar conflicts resolved" },
  { id: 4, date: "2026-03-02", time: "17:02", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.09, durationMs: 35100, turns: 6, notes: "" },
  { id: 5, date: "2026-03-02", time: "19:00", agentId: "health", agentName: "Health Audit", mode: "scheduled", status: "failed", costUsd: 0.05, durationMs: 8200, turns: 2, notes: "vault path not found" },
  { id: 6, date: "2026-03-01", time: "06:00", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.11, durationMs: 39800, turns: 7, notes: "3 emails drafted" },
  { id: 7, date: "2026-03-01", time: "09:00", agentId: "spending", agentName: "Spending Analysis", mode: "scheduled", status: "attention", costUsd: 0.48, durationMs: 182400, turns: 27, notes: "approached budget limit" },
  { id: 8, date: "2026-03-01", time: "17:01", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.10, durationMs: 37600, turns: 7, notes: "Research digest compiled" },
  { id: 9, date: "2026-03-01", time: "19:01", agentId: "health", agentName: "Health Audit", mode: "scheduled", status: "failed", costUsd: 0.04, durationMs: 7100, turns: 2, notes: "vault path not found" },
  { id: 10, date: "2026-02-28", time: "06:01", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.13, durationMs: 45200, turns: 9, notes: "" },
  { id: 11, date: "2026-02-28", time: "16:00", agentId: "daily-weekly", agentName: "Daily Driver (Weekly)", mode: "scheduled", status: "completed", costUsd: 0.31, durationMs: 124800, turns: 18, notes: "Weekly report generated" },
  { id: 12, date: "2026-02-28", time: "17:00", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.07, durationMs: 28900, turns: 4, notes: "" },
  { id: 13, date: "2026-02-27", time: "06:02", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.10, durationMs: 36400, turns: 6, notes: "2 emails drafted" },
  { id: 14, date: "2026-02-27", time: "17:01", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "manual", status: "completed", costUsd: 0.11, durationMs: 41200, turns: 8, notes: "Manual trigger — urgent digest" },
  { id: 15, date: "2026-02-26", time: "06:00", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.09, durationMs: 33100, turns: 5, notes: "" },
  { id: 16, date: "2026-02-26", time: "17:00", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.08, durationMs: 30400, turns: 5, notes: "" },
  { id: 17, date: "2026-02-25", time: "06:01", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.15, durationMs: 52300, turns: 11, notes: "Large calendar sync" },
  { id: 18, date: "2026-02-25", time: "17:02", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "dry-run", status: "completed", costUsd: 0.03, durationMs: 12100, turns: 2, notes: "Dry run — validated config" },
  { id: 19, date: "2026-02-24", time: "06:00", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.12, durationMs: 43600, turns: 8, notes: "" },
  { id: 20, date: "2026-02-24", time: "17:00", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.09, durationMs: 34800, turns: 6, notes: "" },
  { id: 21, date: "2026-02-23", time: "09:01", agentId: "spending", agentName: "Spending Analysis", mode: "scheduled", status: "completed", costUsd: 0.38, durationMs: 156700, turns: 22, notes: "Budget report generated" },
  { id: 22, date: "2026-02-22", time: "06:02", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.11, durationMs: 40100, turns: 7, notes: "" },
  { id: 23, date: "2026-02-21", time: "16:01", agentId: "daily-weekly", agentName: "Daily Driver (Weekly)", mode: "scheduled", status: "completed", costUsd: 0.28, durationMs: 118200, turns: 16, notes: "Weekly report — 4 insights" },
  { id: 24, date: "2026-02-20", time: "06:00", agentId: "daily-morning", agentName: "Daily Driver (Morning)", mode: "scheduled", status: "completed", costUsd: 0.10, durationMs: 37200, turns: 6, notes: "" },
  { id: 25, date: "2026-02-19", time: "17:01", agentId: "daily-evening", agentName: "Daily Driver (Evening)", mode: "scheduled", status: "completed", costUsd: 0.07, durationMs: 27600, turns: 4, notes: "Light digest day" },
];

// --------------------------------------------------------------------------
// Log Output — per agent
// --------------------------------------------------------------------------
export const agentLogs = {
  "daily-morning": [
    "[06:00:01] [INFO] Agent started — scheduled trigger",
    "[06:00:02] [INFO] Loading skill: research-assistant",
    "[06:00:03] [INFO] Loading skill: email-drafting",
    "[06:00:03] [INFO] Loading skill: calendar-sync",
    "[06:00:04] [DEBUG] Vault connection established",
    "[06:00:05] [INFO] Reading calendar events for Mar 3",
    "[06:00:08] [INFO] Found 4 events, 1 conflict detected",
    "[06:00:10] [INFO] Resolving conflict: standup vs. deep work block",
    "[06:00:12] [WARN] Deep work block moved to 2:00 PM",
    "[06:00:15] [INFO] Scanning inbox — 12 unread messages",
    "[06:00:20] [INFO] Prioritized 3 messages for draft response",
    "[06:00:25] [DEBUG] Generating draft for: Q1 Budget Review request",
    "[06:00:30] [INFO] Draft saved: email-draft-001.md",
    "[06:00:32] [DEBUG] Generating draft for: Vendor follow-up",
    "[06:00:36] [INFO] Draft saved: email-draft-002.md",
    "[06:00:38] [DEBUG] Generating draft for: Team lunch RSVP",
    "[06:00:40] [INFO] Draft saved: email-draft-003.md",
    "[06:00:42] [INFO] Research task: market brief on AI agents",
    "[06:00:55] [INFO] Brief compiled — 3 sources, 420 words",
    "[06:01:00] [INFO] File written: daily-brief-2026-03-03.md",
    "[06:01:02] [DEBUG] Syncing calendar changes",
    "[06:01:05] [INFO] Calendar sync complete",
    "[06:01:08] [INFO] Generating daily summary",
    "[06:01:10] [INFO] Summary: 3 drafts, 1 conflict resolved, 1 brief",
    "[06:01:12] [INFO] Run complete — 8 turns, $0.12",
    "[06:01:12] [DEBUG] Releasing vault connection",
    "[06:01:13] [INFO] Agent stopped — all tasks complete",
  ],
  "daily-evening": [
    "[17:00:01] [INFO] Agent started — scheduled trigger",
    "[17:00:02] [INFO] Loading skill: research-assistant",
    "[17:00:02] [INFO] Loading skill: email-drafting",
    "[17:00:03] [INFO] Loading skill: slack-digest",
    "[17:00:04] [DEBUG] Vault connection established",
    "[17:00:05] [INFO] Scanning Slack channels — 8 channels",
    "[17:00:10] [INFO] Found 47 messages since morning run",
    "[17:00:12] [DEBUG] Filtering for actionable items",
    "[17:00:15] [INFO] 6 actionable items identified",
    "[17:00:18] [INFO] Generating Slack digest",
    "[17:00:22] [INFO] Digest compiled — 6 items, 3 threads",
    "[17:00:25] [DEBUG] Checking for evening inbox updates",
    "[17:00:28] [INFO] 5 new messages since morning",
    "[17:00:30] [INFO] No urgent drafts needed",
    "[17:00:32] [INFO] Compiling research updates",
    "[17:00:38] [INFO] 2 new articles on tracked topics",
    "[17:00:42] [INFO] Evening brief written: evening-2026-03-03.md",
    "[17:00:44] [INFO] Run in progress — 3 turns so far",
    "[17:00:45] [DEBUG] Continuing task queue...",
  ],
  "daily-weekly": [
    "[16:00:01] [INFO] Agent started — scheduled trigger (weekly)",
    "[16:00:02] [INFO] Loading skill: research-assistant",
    "[16:00:02] [INFO] Loading skill: weekly-report",
    "[16:00:03] [INFO] Loading skill: notion-sync",
    "[16:00:04] [DEBUG] Vault connection established",
    "[16:00:05] [INFO] Aggregating daily runs from Feb 22–28",
    "[16:00:10] [INFO] Found 14 runs across 3 agents",
    "[16:00:12] [INFO] Calculating weekly cost: $1.68",
    "[16:00:15] [DEBUG] Compiling completion rates",
    "[16:00:18] [INFO] Completion rate: 92% (13/14 succeeded)",
    "[16:00:20] [WARN] 1 failed run: Health Audit on Feb 28",
    "[16:00:22] [INFO] Generating weekly insights",
    "[16:00:30] [INFO] Insight 1: Calendar conflicts trending up",
    "[16:00:33] [INFO] Insight 2: Email draft acceptance rate: 78%",
    "[16:00:36] [INFO] Insight 3: Spending agent near budget limit",
    "[16:00:38] [INFO] Insight 4: Slack digest volume +12% WoW",
    "[16:00:42] [INFO] Writing weekly report",
    "[16:00:50] [INFO] Report saved: weekly-2026-02-28.md",
    "[16:00:52] [DEBUG] Syncing to Notion workspace",
    "[16:00:58] [INFO] Notion page created: Weekly Report — Feb 28",
    "[16:01:02] [INFO] Notion database updated with metrics",
    "[16:01:05] [INFO] Archiving daily logs",
    "[16:01:10] [INFO] 7 daily logs archived to /archive/feb-w4/",
    "[16:01:12] [DEBUG] Cleaning temp files",
    "[16:01:15] [INFO] Weekly summary generated",
    "[16:01:18] [INFO] Run complete — 18 turns, $0.31",
    "[16:01:19] [DEBUG] Releasing vault connection",
    "[16:01:20] [INFO] Agent stopped — weekly cycle complete",
  ],
  "spending": [
    "[09:00:01] [INFO] Agent started — scheduled trigger",
    "[09:00:02] [INFO] Loading skill: finance-analysis",
    "[09:00:02] [INFO] Loading skill: csv-parser",
    "[09:00:03] [INFO] Loading skill: budget-alerts",
    "[09:00:04] [DEBUG] Vault connection established",
    "[09:00:05] [INFO] Reading transaction export: transactions-2026-02.csv",
    "[09:00:08] [INFO] Parsed 342 transactions",
    "[09:00:10] [DEBUG] Categorizing transactions",
    "[09:00:18] [INFO] Categories: groceries(89), dining(47), transport(34), subscriptions(22), other(150)",
    "[09:00:22] [INFO] Computing monthly totals",
    "[09:00:25] [INFO] Feb total: $3,847.22",
    "[09:00:28] [WARN] Dining category +23% over Jan",
    "[09:00:30] [INFO] Generating budget comparison",
    "[09:00:35] [WARN] 3 categories over budget threshold",
    "[09:00:38] [INFO] Subscriptions audit: 22 active, 3 unused",
    "[09:00:42] [WARN] Unused: streaming-svc-2, cloud-storage-old, magazine-digital",
    "[09:00:45] [INFO] Potential savings: $47.97/mo",
    "[09:00:48] [INFO] Running trend analysis (6-month window)",
    "[09:00:55] [INFO] Trend: overall spending +8% MoM",
    "[09:01:00] [INFO] Generating spending report",
    "[09:01:10] [INFO] Report saved: spending-feb-2026.md",
    "[09:01:12] [DEBUG] Checking budget alerts",
    "[09:01:15] [WARN] Agent cost approaching budget limit ($0.48 / $0.50)",
    "[09:01:18] [INFO] Triggering budget alert notification",
    "[09:01:20] [INFO] Alert sent — budget usage at 96%",
    "[09:01:22] [DEBUG] Attempting additional analysis",
    "[09:01:25] [WARN] Remaining budget insufficient for deep analysis",
    "[09:01:28] [INFO] Skipping: investment comparison (estimated $0.08)",
    "[09:01:30] [INFO] Run complete — 27 turns, $0.48",
    "[09:01:31] [WARN] Note: approached budget limit",
    "[09:01:32] [INFO] Agent stopped — budget constrained",
  ],
  "inbox": [
    "[--:--:--] [INFO] Agent has never been run",
    "[--:--:--] [INFO] Status: disabled",
    "[--:--:--] [INFO] Enable this agent to begin processing inbox",
    "[--:--:--] [DEBUG] Configured skills: email-triage, label-manager",
    "[--:--:--] [INFO] Schedule: Daily 8:00 AM (cron: 0 8 * * *)",
    "[--:--:--] [INFO] Permission mode: acceptEdits",
  ],
  "health": [
    "[19:00:01] [INFO] Agent started — scheduled trigger",
    "[19:00:02] [INFO] Loading skill: vault-reader",
    "[19:00:02] [INFO] Loading skill: health-metrics",
    "[19:00:03] [DEBUG] Attempting vault connection",
    "[19:00:04] [ERROR] Vault path not found: /data/health/metrics.json",
    "[19:00:05] [DEBUG] Retrying with fallback path",
    "[19:00:06] [ERROR] Fallback path also not found: /data/health/backup/metrics.json",
    "[19:00:07] [WARN] No health data source available",
    "[19:00:08] [INFO] Run failed — 2 turns, $0.05",
    "[19:00:08] [ERROR] Fatal: vault path not found",
    "[19:00:09] [INFO] Agent stopped — error state",
    "[19:00:09] [DEBUG] Error logged to /logs/health-error-2026-03-01.log",
  ],
};

// --------------------------------------------------------------------------
// Cost History — 30 data points for Recharts
// --------------------------------------------------------------------------
export const costHistory = [
  { date: "Feb 1", cost: 0.08 },
  { date: "Feb 2", cost: 0.12 },
  { date: "Feb 3", cost: 0.11 },
  { date: "Feb 4", cost: 0.09 },
  { date: "Feb 5", cost: 0.14 },
  { date: "Feb 6", cost: 0.10 },
  { date: "Feb 7", cost: 0.13 },
  { date: "Feb 8", cost: 0.22 },
  { date: "Feb 9", cost: 0.45 },
  { date: "Feb 10", cost: 0.11 },
  { date: "Feb 11", cost: 0.08 },
  { date: "Feb 12", cost: 0.15 },
  { date: "Feb 13", cost: 0.09 },
  { date: "Feb 14", cost: 0.12 },
  { date: "Feb 15", cost: 0.10 },
  { date: "Feb 16", cost: 0.42 },
  { date: "Feb 17", cost: 0.14 },
  { date: "Feb 18", cost: 0.08 },
  { date: "Feb 19", cost: 0.11 },
  { date: "Feb 20", cost: 0.13 },
  { date: "Feb 21", cost: 0.28 },
  { date: "Feb 22", cost: 0.10 },
  { date: "Feb 23", cost: 0.38 },
  { date: "Feb 24", cost: 0.12 },
  { date: "Feb 25", cost: 0.15 },
  { date: "Feb 26", cost: 0.09 },
  { date: "Feb 27", cost: 0.11 },
  { date: "Feb 28", cost: 0.31 },
  { date: "Mar 1", cost: 0.48 },
  { date: "Mar 2", cost: 0.14 },
];
